param(
    [string]$ClientDataRoot = "",
    [int]$ScreenWidth = 1920,
    [int]$ScreenHeight = 1080
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ClientToolsRoot = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
. (Join-Path $ScriptDir "Resolve-NikamiWorkspace.ps1")
$WorkspaceRoot = Get-NikamiWorkspaceRoot -ClientToolsRoot $ClientToolsRoot
if ([string]::IsNullOrWhiteSpace($ClientDataRoot)) {
    $ClientDataRoot = Get-NikamiRuntimeClientRoot -WorkspaceRoot $WorkspaceRoot
}

if (!(Test-Path -LiteralPath $ClientDataRoot)) {
    throw "Client data directory not found: $ClientDataRoot"
}

$resolvedRoot = (Resolve-Path -LiteralPath $ClientDataRoot).Path
if (!$resolvedRoot.StartsWith($WorkspaceRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to clean outside workspace root $($WorkspaceRoot): $resolvedRoot"
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupDir = Join-Path $resolvedRoot "_clean-backups\$stamp"
$quarantineDir = Join-Path $resolvedRoot "_quarantine_dx11\$stamp"
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
New-Item -ItemType Directory -Force -Path $quarantineDir | Out-Null

foreach ($cfg in @("options.cfg", "user.cfg")) {
    $path = Join-Path $resolvedRoot $cfg
    if (Test-Path -LiteralPath $path) {
        Copy-Item -LiteralPath $path -Destination (Join-Path $backupDir $cfg) -Force
    }
}

$localMachineOptionsPath = Join-Path $resolvedRoot "local_machine_options.iff"
if (Test-Path -LiteralPath $localMachineOptionsPath) {
    Move-Item -LiteralPath $localMachineOptionsPath -Destination (Join-Path $backupDir "local_machine_options.iff") -Force
}

$overridePath = Join-Path $resolvedRoot "misc\override.cfg"
if (Test-Path -LiteralPath $overridePath) {
    New-Item -ItemType Directory -Force -Path (Join-Path $backupDir "misc") | Out-Null
    Copy-Item -LiteralPath $overridePath -Destination (Join-Path $backupDir "misc\override.cfg") -Force
}

$taintedNames = @(
    "gl08_r.dll",
    "gl08_r.pdb",
    "d3d9.dll",
    "d3d9.dll.bak",
    "d3d9.dll.old",
    "d3d9.dll.old2",
    "d3d9.dlls"
)

$moved = foreach ($name in $taintedNames) {
    $path = Join-Path $resolvedRoot $name
    if (Test-Path -LiteralPath $path) {
        $dest = Join-Path $quarantineDir $name
        Move-Item -LiteralPath $path -Destination $dest -Force
        $dest
    }
}

$staleShaderIncludeOverrides = @(
    "vertex_program\include\functions.inc",
    "extracted_slot_def\vertex_program\include\functions.inc"
)

foreach ($relativePath in $staleShaderIncludeOverrides) {
    $path = Join-Path $resolvedRoot $relativePath
    if (Test-Path -LiteralPath $path) {
        $hasCurrentViewerDirectionHelper = Select-String -LiteralPath $path -Pattern "calculateViewerDirection_w" -Quiet
        if (!$hasCurrentViewerDirectionHelper) {
            $dest = Join-Path $quarantineDir $relativePath
            New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dest) | Out-Null
            Move-Item -LiteralPath $path -Destination $dest -Force
            $moved += $dest
        }
    }
}

$options = @"
# options.cfg - clean OG D3D9 runtime profile generated by scripts/dev/clean-og-client-runtime.ps1.

[ClientAudio]
	enabled=true
	masterVolume=1.0
	soundEffectVolume=1.0
	backGroundMusicVolume=1.0
	playerMusicVolume=1.0
	userInterfaceVolume=1.0
	ambientEffectVolume=1.0
	soundProvider="5.1 Speakers"

[ClientGame]
	skipIntro=1
	cameraFarPlane=16384
	cameraFarPlaneSpace=32768

[ClientGraphics]
	useHardwareMouseCursor=1
	screenWidth=$ScreenWidth
	screenHeight=$ScreenHeight
	windowed=true
	useSafeRenderer=1
	rasterMajor=5
	disableOcclusionCulling=true
	dpvsMinimumObjectWidth=0.0
	dpvsMinimumObjectHeight=0.0
	dpvsMinimumObjectOpacity=0.0
	dpvsImageScale=1.0
	discardHighestMipMapLevels=0
	discardHighestNormalMipMapLevels=0
	loadAllAssetsRegardlessOfShaderCapability=true

[Direct3d9]
	disableVertexAndPixelShaders=true
	fullscreenRefreshRate=60

[Direct3d11]
	modernShadows=true
	modernShadowQuality=4
	modernShadowCascadeCount=4
	modernShadowMapSize=4096
	modernShadowDistance=512.0
	modernShadowSplitLambda=0.85
	modernShadowStabilize=true
	modernShadowFilter=2
	modernShadowPcfTaps=32
	modernShadowFilterRadius=2.50
	modernShadowDepthBias=0.0008
	modernShadowSlopeBias=2.0
	modernShadowNormalBias=0.05
	modernShadowFadeStart=0.85
	modernShadowContactShadows=true
	modernShadowContactDistance=12.0
	modernShadowVrSinglePass=true
	modernShadowMaxCasters=4096
	modernShadowTerrain=true
	modernShadowCharacters=true
	modernShadowObjects=true
	legacyStencilShadowsInVr=false

[SharedUtility]
	cache=misc/cache_large.iff
"@

$user = @"
# user.cfg - stable OG runtime profile generated by scripts/dev/clean-og-client-runtime.ps1.

[SwgClient]
	allowMultipleInstances=true

[Station]
	gameFeatures=0xffffffff
	subscriptionFeatures=0x01

[ClientGame]
	skipIntro=1
	disableCutScenes=1
	skipSplash=1
	cameraFarPlane=16384
	cameraFarPlaneSpace=32768
	freeChaseCameraMaximumZoom=30

[ClientSkeletalAnimation]
	lodManagerEnable=true
	lodManagerFirstLodCount=128.0
	lodManagerEveryOtherFrameSkinningCharacterCount=256
	lodManagerHardSkinningCharacterCount=128

[ClientObject]
	forceLowDetailLevels=false
	forceHighDetailLevels=true
	detailLevelBias=8.0
	detailLevelStretch=100.0
	detailOverlapFraction=1.0
	detailOverlapCap=250.0
	preloadDetailLevels=true
	fadeInEnabled=true
	crossFadeEnabled=true
	renderShadows=false
	shadowDetailLevel=1.0
	volumetricShadowDistanceLevel=1.0
	meshShadows=false
	skeletalShadows=0

[ClientTerrain]
	enableFlora=true
	dynamicFarFloraEnabled=true
	dynamicNearFloraEnabled=true
	dynamicNearFloraDistance=64.0
	staticNonCollidableFloraEnabled=true
	staticNonCollidableFloraDistance=128.0
	preloadGroups=true
	maximumNumberOfChunksAllowed=131072

[ClientProceduralTerrainAppearance_LevelOfDetail]
	useHeightBias=true
	forceHighThreshold=30.0
	threshold=8.0
	heightBiasFactor=12.0
	heightBiasMax=100

[ClientParticle]
	disable=false
	maxQuadParticles=2048
	maxMeshParticles=512
	maxParticleAttachments=1024
	minGlobalLodDistance=0.0
	maxGlobalLodDistance=4096.0
	swooshCullDistance=4096.0
	particleUserLimit=2048

[ParticleEffectAppearance]
	globalLodBias=1.0
	globalUserLimit=2048

[SharedTerrain]
	maximumNumberOfChunksAllowed=131072
	disableFloraCaching=false

[SharedUtility/WorldSnapshot]
	detailLevelBias=1.0

[ClientUserInterface]
	debugExamine=0
	debugClipboardExamine=0
	allowTargetAnything=1
	drawNetworkIds=0

[SharedFoundation]
	minFrameRate=1.0f
	frameRateLimit=0.0f

[ClientGraphics]
	screenWidth=$ScreenWidth
	screenHeight=$ScreenHeight
	windowed=true
	useSafeRenderer=1
	rasterMajor=5
	disableOcclusionCulling=true
	dpvsMinimumObjectWidth=0.0
	dpvsMinimumObjectHeight=0.0
	dpvsMinimumObjectOpacity=0.0
	dpvsImageScale=1.0
	discardHighestMipMapLevels=0
	discardHighestNormalMipMapLevels=0
	loadAllAssetsRegardlessOfShaderCapability=true

[Direct3d11]
	modernShadows=true
	modernShadowQuality=4
	modernShadowCascadeCount=4
	modernShadowMapSize=4096
	modernShadowDistance=512.0
	modernShadowSplitLambda=0.85
	modernShadowStabilize=true
	modernShadowFilter=2
	modernShadowPcfTaps=32
	modernShadowFilterRadius=2.50
	modernShadowDepthBias=0.0008
	modernShadowSlopeBias=2.0
	modernShadowNormalBias=0.05
	modernShadowFadeStart=0.85
	modernShadowContactShadows=true
	modernShadowContactDistance=12.0
	modernShadowVrSinglePass=true
	modernShadowMaxCasters=4096
	modernShadowTerrain=true
	modernShadowCharacters=true
	modernShadowObjects=true
	legacyStencilShadowsInVr=false
"@

$override = @"
# misc/override.cfg - clean OG D3D9 localhost profile generated by scripts/dev/clean-og-client-runtime.ps1.

[ClientGraphics]
windowed=true
borderlessWindow=false
constrainMouseCursorToWindow=false
useHardwareMouseCursor=true
useSafeRenderer=1
rasterMajor=5
screenWidth=$ScreenWidth
screenHeight=$ScreenHeight
disableOcclusionCulling=true
dpvsMinimumObjectWidth=0.0
dpvsMinimumObjectHeight=0.0
dpvsMinimumObjectOpacity=0.0
dpvsImageScale=1.0
discardHighestMipMapLevels=0
discardHighestNormalMipMapLevels=0
loadAllAssetsRegardlessOfShaderCapability=true

[Direct3d9]
disableVertexAndPixelShaders=true
shaderCapabilityOverride=0
fullscreenRefreshRate=60

[Direct3d11]
modernShadows=true
modernShadowQuality=4
modernShadowCascadeCount=4
modernShadowMapSize=4096
modernShadowDistance=512.0
modernShadowSplitLambda=0.85
modernShadowStabilize=true
modernShadowFilter=2
modernShadowPcfTaps=32
modernShadowFilterRadius=2.50
modernShadowDepthBias=0.0008
modernShadowSlopeBias=2.0
modernShadowNormalBias=0.05
modernShadowFadeStart=0.85
modernShadowContactShadows=true
modernShadowContactDistance=12.0
modernShadowVrSinglePass=true
modernShadowMaxCasters=4096
modernShadowTerrain=true
modernShadowCharacters=true
modernShadowObjects=true
legacyStencilShadowsInVr=false

[SwgClient]
allowMultipleInstances=true

[SharedFoundation]
minFrameRate=1.0f
frameRateLimit=0.0f

[ClientGame]
skipIntro=1
disableCutScenes=1
skipSplash=1
cameraFarPlane=16384
cameraFarPlaneSpace=32768
freeChaseCameraMaximumZoom=30
loginServerAddress0=127.0.0.1
loginServerPort0=44453

[ClientObject]
forceLowDetailLevels=false
forceHighDetailLevels=true
detailLevelBias=8.0
detailLevelStretch=100.0
detailOverlapFraction=1.0
detailOverlapCap=250.0
preloadDetailLevels=true
fadeInEnabled=true
crossFadeEnabled=true
renderShadows=false
shadowDetailLevel=1.0
volumetricShadowDistanceLevel=1.0
meshShadows=false
skeletalShadows=0

[ClientSkeletalAnimation]
lodManagerEnable=true
lodManagerFirstLodCount=128.0
lodManagerEveryOtherFrameSkinningCharacterCount=256
lodManagerHardSkinningCharacterCount=128

[ClientTerrain]
enableFlora=true
dynamicFarFloraEnabled=true
dynamicNearFloraEnabled=true
dynamicNearFloraDistance=64.0
staticNonCollidableFloraEnabled=true
staticNonCollidableFloraDistance=128.0
preloadGroups=true
maximumNumberOfChunksAllowed=131072

[ClientProceduralTerrainAppearance_LevelOfDetail]
useHeightBias=true
forceHighThreshold=30.0
threshold=8.0
heightBiasFactor=12.0
heightBiasMax=100

[ClientParticle]
disable=false
maxQuadParticles=2048
maxMeshParticles=512
maxParticleAttachments=1024
minGlobalLodDistance=0.0
maxGlobalLodDistance=4096.0
swooshCullDistance=4096.0
particleUserLimit=2048

[ParticleEffectAppearance]
globalLodBias=1.0
globalUserLimit=2048

[SharedTerrain]
maximumNumberOfChunksAllowed=131072
disableFloraCaching=false

[SharedUtility/WorldSnapshot]
detailLevelBias=1.0

[ClientAudio]
enabled=true
masterVolume=1.0
soundEffectVolume=1.0
backGroundMusicVolume=1.0
playerMusicVolume=1.0
userInterfaceVolume=1.0
ambientEffectVolume=1.0
soundProvider="5.1 Speakers"
"@

Set-Content -LiteralPath (Join-Path $resolvedRoot "options.cfg") -Value $options
Set-Content -LiteralPath (Join-Path $resolvedRoot "user.cfg") -Value $user
New-Item -ItemType Directory -Force -Path (Join-Path $resolvedRoot "misc") | Out-Null
Set-Content -LiteralPath $overridePath -Value $override

[pscustomobject]@{
    ClientDataRoot = $resolvedRoot
    BackupDir = $backupDir
    QuarantineDir = $quarantineDir
    Moved = @($moved)
    Renderer = "Direct3d9 gl05_r.dll"
    RasterMajor = 5
    OverrideCfg = $overridePath
}
